// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: internal/api/ingest.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TableIdentifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Catalog       string                 `protobuf:"bytes,1,opt,name=catalog,proto3" json:"catalog,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Table         string                 `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableIdentifier) Reset() {
	*x = TableIdentifier{}
	mi := &file_internal_api_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableIdentifier) ProtoMessage() {}

func (x *TableIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableIdentifier.ProtoReflect.Descriptor instead.
func (*TableIdentifier) Descriptor() ([]byte, []int) {
	return file_internal_api_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *TableIdentifier) GetCatalog() string {
	if x != nil {
		return x.Catalog
	}
	return ""
}

func (x *TableIdentifier) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *TableIdentifier) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

type DistributedSnapshot struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId       int64                  `protobuf:"varint,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	ParentSnapshotId int64                  `protobuf:"varint,2,opt,name=parent_snapshot_id,json=parentSnapshotId,proto3" json:"parent_snapshot_id,omitempty"`
	CommitUuid       string                 `protobuf:"bytes,3,opt,name=commit_uuid,json=commitUuid,proto3" json:"commit_uuid,omitempty"`
	Properties       map[string]string      `protobuf:"bytes,4,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DistributedSnapshot) Reset() {
	*x = DistributedSnapshot{}
	mi := &file_internal_api_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistributedSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistributedSnapshot) ProtoMessage() {}

func (x *DistributedSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistributedSnapshot.ProtoReflect.Descriptor instead.
func (*DistributedSnapshot) Descriptor() ([]byte, []int) {
	return file_internal_api_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *DistributedSnapshot) GetSnapshotId() int64 {
	if x != nil {
		return x.SnapshotId
	}
	return 0
}

func (x *DistributedSnapshot) GetParentSnapshotId() int64 {
	if x != nil {
		return x.ParentSnapshotId
	}
	return 0
}

func (x *DistributedSnapshot) GetCommitUuid() string {
	if x != nil {
		return x.CommitUuid
	}
	return ""
}

func (x *DistributedSnapshot) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Partitions    []string               `protobuf:"bytes,2,rep,name=partitions,proto3" json:"partitions,omitempty"`
	DataSource    string                 `protobuf:"bytes,3,opt,name=data_source,json=dataSource,proto3" json:"data_source,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_internal_api_ingest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_ingest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_internal_api_ingest_proto_rawDescGZIP(), []int{2}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetPartitions() []string {
	if x != nil {
		return x.Partitions
	}
	return nil
}

func (x *Task) GetDataSource() string {
	if x != nil {
		return x.DataSource
	}
	return ""
}

func (x *Task) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type StartJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         *TableIdentifier       `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Requester     string                 `protobuf:"bytes,2,opt,name=requester,proto3" json:"requester,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartJobRequest) Reset() {
	*x = StartJobRequest{}
	mi := &file_internal_api_ingest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartJobRequest) ProtoMessage() {}

func (x *StartJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_ingest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartJobRequest.ProtoReflect.Descriptor instead.
func (*StartJobRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_ingest_proto_rawDescGZIP(), []int{3}
}

func (x *StartJobRequest) GetTable() *TableIdentifier {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *StartJobRequest) GetRequester() string {
	if x != nil {
		return x.Requester
	}
	return ""
}

type StartJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Table         *TableIdentifier       `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Snapshot      *DistributedSnapshot   `protobuf:"bytes,3,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Tasks         []*Task                `protobuf:"bytes,4,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartJobResponse) Reset() {
	*x = StartJobResponse{}
	mi := &file_internal_api_ingest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartJobResponse) ProtoMessage() {}

func (x *StartJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_ingest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartJobResponse.ProtoReflect.Descriptor instead.
func (*StartJobResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_ingest_proto_rawDescGZIP(), []int{4}
}

func (x *StartJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *StartJobResponse) GetTable() *TableIdentifier {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *StartJobResponse) GetSnapshot() *DistributedSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *StartJobResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type CommitJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Table         *TableIdentifier       `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	SnapshotId    int64                  `protobuf:"varint,3,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	ManifestPaths []string               `protobuf:"bytes,4,rep,name=manifest_paths,json=manifestPaths,proto3" json:"manifest_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitJobRequest) Reset() {
	*x = CommitJobRequest{}
	mi := &file_internal_api_ingest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitJobRequest) ProtoMessage() {}

func (x *CommitJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_ingest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitJobRequest.ProtoReflect.Descriptor instead.
func (*CommitJobRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_ingest_proto_rawDescGZIP(), []int{5}
}

func (x *CommitJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CommitJobRequest) GetTable() *TableIdentifier {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *CommitJobRequest) GetSnapshotId() int64 {
	if x != nil {
		return x.SnapshotId
	}
	return 0
}

func (x *CommitJobRequest) GetManifestPaths() []string {
	if x != nil {
		return x.ManifestPaths
	}
	return nil
}

type CommitJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Committed     bool                   `protobuf:"varint,2,opt,name=committed,proto3" json:"committed,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitJobResponse) Reset() {
	*x = CommitJobResponse{}
	mi := &file_internal_api_ingest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitJobResponse) ProtoMessage() {}

func (x *CommitJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_ingest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitJobResponse.ProtoReflect.Descriptor instead.
func (*CommitJobResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_ingest_proto_rawDescGZIP(), []int{6}
}

func (x *CommitJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CommitJobResponse) GetCommitted() bool {
	if x != nil {
		return x.Committed
	}
	return false
}

func (x *CommitJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReportManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Table         *TableIdentifier       `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	SnapshotId    int64                  `protobuf:"varint,3,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,4,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	ManifestPaths []string               `protobuf:"bytes,5,rep,name=manifest_paths,json=manifestPaths,proto3" json:"manifest_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportManifestRequest) Reset() {
	*x = ReportManifestRequest{}
	mi := &file_internal_api_ingest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportManifestRequest) ProtoMessage() {}

func (x *ReportManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_ingest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportManifestRequest.ProtoReflect.Descriptor instead.
func (*ReportManifestRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_ingest_proto_rawDescGZIP(), []int{7}
}

func (x *ReportManifestRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ReportManifestRequest) GetTable() *TableIdentifier {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *ReportManifestRequest) GetSnapshotId() int64 {
	if x != nil {
		return x.SnapshotId
	}
	return 0
}

func (x *ReportManifestRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *ReportManifestRequest) GetManifestPaths() []string {
	if x != nil {
		return x.ManifestPaths
	}
	return nil
}

type ReportManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportManifestResponse) Reset() {
	*x = ReportManifestResponse{}
	mi := &file_internal_api_ingest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportManifestResponse) ProtoMessage() {}

func (x *ReportManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_ingest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportManifestResponse.ProtoReflect.Descriptor instead.
func (*ReportManifestResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_ingest_proto_rawDescGZIP(), []int{8}
}

func (x *ReportManifestResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ReportManifestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AssignTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignTasksRequest) Reset() {
	*x = AssignTasksRequest{}
	mi := &file_internal_api_ingest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignTasksRequest) ProtoMessage() {}

func (x *AssignTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_ingest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignTasksRequest.ProtoReflect.Descriptor instead.
func (*AssignTasksRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_ingest_proto_rawDescGZIP(), []int{9}
}

func (x *AssignTasksRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *AssignTasksRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type AssignTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Table         *TableIdentifier       `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Snapshot      *DistributedSnapshot   `protobuf:"bytes,3,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Tasks         []*Task                `protobuf:"bytes,4,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignTasksResponse) Reset() {
	*x = AssignTasksResponse{}
	mi := &file_internal_api_ingest_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignTasksResponse) ProtoMessage() {}

func (x *AssignTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_ingest_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignTasksResponse.ProtoReflect.Descriptor instead.
func (*AssignTasksResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_ingest_proto_rawDescGZIP(), []int{10}
}

func (x *AssignTasksResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *AssignTasksResponse) GetTable() *TableIdentifier {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *AssignTasksResponse) GetSnapshot() *DistributedSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *AssignTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_internal_api_ingest_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_ingest_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_ingest_proto_rawDescGZIP(), []int{11}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Instructions  string                 `protobuf:"bytes,2,opt,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_internal_api_ingest_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_ingest_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_ingest_proto_rawDescGZIP(), []int{12}
}

func (x *HeartbeatResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HeartbeatResponse) GetInstructions() string {
	if x != nil {
		return x.Instructions
	}
	return ""
}

var File_internal_api_ingest_proto protoreflect.FileDescriptor

const file_internal_api_ingest_proto_rawDesc = "" +
	"\n" +
	"\x19internal/api/ingest.proto\x12\x03api\"_\n" +
	"\x0fTableIdentifier\x12\x18\n" +
	"\acatalog\x18\x01 \x01(\tR\acatalog\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05table\x18\x03 \x01(\tR\x05table\"\x8e\x02\n" +
	"\x13DistributedSnapshot\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\x03R\n" +
	"snapshotId\x12,\n" +
	"\x12parent_snapshot_id\x18\x02 \x01(\x03R\x10parentSnapshotId\x12\x1f\n" +
	"\vcommit_uuid\x18\x03 \x01(\tR\n" +
	"commitUuid\x12H\n" +
	"\n" +
	"properties\x18\x04 \x03(\v2(.api.DistributedSnapshot.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x01\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1e\n" +
	"\n" +
	"partitions\x18\x02 \x03(\tR\n" +
	"partitions\x12\x1f\n" +
	"\vdata_source\x18\x03 \x01(\tR\n" +
	"dataSource\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"[\n" +
	"\x0fStartJobRequest\x12*\n" +
	"\x05table\x18\x01 \x01(\v2\x14.api.TableIdentifierR\x05table\x12\x1c\n" +
	"\trequester\x18\x02 \x01(\tR\trequester\"\xac\x01\n" +
	"\x10StartJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12*\n" +
	"\x05table\x18\x02 \x01(\v2\x14.api.TableIdentifierR\x05table\x124\n" +
	"\bsnapshot\x18\x03 \x01(\v2\x18.api.DistributedSnapshotR\bsnapshot\x12\x1f\n" +
	"\x05tasks\x18\x04 \x03(\v2\t.api.TaskR\x05tasks\"\x9d\x01\n" +
	"\x10CommitJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12*\n" +
	"\x05table\x18\x02 \x01(\v2\x14.api.TableIdentifierR\x05table\x12\x1f\n" +
	"\vsnapshot_id\x18\x03 \x01(\x03R\n" +
	"snapshotId\x12%\n" +
	"\x0emanifest_paths\x18\x04 \x03(\tR\rmanifestPaths\"b\n" +
	"\x11CommitJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1c\n" +
	"\tcommitted\x18\x02 \x01(\bR\tcommitted\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xbf\x01\n" +
	"\x15ReportManifestRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12*\n" +
	"\x05table\x18\x02 \x01(\v2\x14.api.TableIdentifierR\x05table\x12\x1f\n" +
	"\vsnapshot_id\x18\x03 \x01(\x03R\n" +
	"snapshotId\x12\x1b\n" +
	"\tworker_id\x18\x04 \x01(\tR\bworkerId\x12%\n" +
	"\x0emanifest_paths\x18\x05 \x03(\tR\rmanifestPaths\"N\n" +
	"\x16ReportManifestResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"H\n" +
	"\x12AssignTasksRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\"\xaf\x01\n" +
	"\x13AssignTasksResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12*\n" +
	"\x05table\x18\x02 \x01(\v2\x14.api.TableIdentifierR\x05table\x124\n" +
	"\bsnapshot\x18\x03 \x01(\v2\x18.api.DistributedSnapshotR\bsnapshot\x12\x1f\n" +
	"\x05tasks\x18\x04 \x03(\v2\t.api.TaskR\x05tasks\"^\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"Q\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\"\n" +
	"\finstructions\x18\x02 \x01(\tR\finstructions2\xcd\x01\n" +
	"\vCoordinator\x127\n" +
	"\bStartJob\x12\x14.api.StartJobRequest\x1a\x15.api.StartJobResponse\x12:\n" +
	"\tCommitJob\x12\x15.api.CommitJobRequest\x1a\x16.api.CommitJobResponse\x12I\n" +
	"\x0eReportManifest\x12\x1a.api.ReportManifestRequest\x1a\x1b.api.ReportManifestResponse2\x86\x01\n" +
	"\x06Worker\x12@\n" +
	"\vAssignTasks\x12\x17.api.AssignTasksRequest\x1a\x18.api.AssignTasksResponse\x12:\n" +
	"\tHeartbeat\x12\x15.api.HeartbeatRequest\x1a\x16.api.HeartbeatResponseB8Z6github.com/example/distributed-ingest/internal/api;apib\x06proto3"

var (
	file_internal_api_ingest_proto_rawDescOnce sync.Once
	file_internal_api_ingest_proto_rawDescData []byte
)

func file_internal_api_ingest_proto_rawDescGZIP() []byte {
	file_internal_api_ingest_proto_rawDescOnce.Do(func() {
		file_internal_api_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_ingest_proto_rawDesc), len(file_internal_api_ingest_proto_rawDesc)))
	})
	return file_internal_api_ingest_proto_rawDescData
}

var file_internal_api_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_internal_api_ingest_proto_goTypes = []any{
	(*TableIdentifier)(nil),        // 0: api.TableIdentifier
	(*DistributedSnapshot)(nil),    // 1: api.DistributedSnapshot
	(*Task)(nil),                   // 2: api.Task
	(*StartJobRequest)(nil),        // 3: api.StartJobRequest
	(*StartJobResponse)(nil),       // 4: api.StartJobResponse
	(*CommitJobRequest)(nil),       // 5: api.CommitJobRequest
	(*CommitJobResponse)(nil),      // 6: api.CommitJobResponse
	(*ReportManifestRequest)(nil),  // 7: api.ReportManifestRequest
	(*ReportManifestResponse)(nil), // 8: api.ReportManifestResponse
	(*AssignTasksRequest)(nil),     // 9: api.AssignTasksRequest
	(*AssignTasksResponse)(nil),    // 10: api.AssignTasksResponse
	(*HeartbeatRequest)(nil),       // 11: api.HeartbeatRequest
	(*HeartbeatResponse)(nil),      // 12: api.HeartbeatResponse
	nil,                            // 13: api.DistributedSnapshot.PropertiesEntry
}
var file_internal_api_ingest_proto_depIdxs = []int32{
	13, // 0: api.DistributedSnapshot.properties:type_name -> api.DistributedSnapshot.PropertiesEntry
	0,  // 1: api.StartJobRequest.table:type_name -> api.TableIdentifier
	0,  // 2: api.StartJobResponse.table:type_name -> api.TableIdentifier
	1,  // 3: api.StartJobResponse.snapshot:type_name -> api.DistributedSnapshot
	2,  // 4: api.StartJobResponse.tasks:type_name -> api.Task
	0,  // 5: api.CommitJobRequest.table:type_name -> api.TableIdentifier
	0,  // 6: api.ReportManifestRequest.table:type_name -> api.TableIdentifier
	0,  // 7: api.AssignTasksResponse.table:type_name -> api.TableIdentifier
	1,  // 8: api.AssignTasksResponse.snapshot:type_name -> api.DistributedSnapshot
	2,  // 9: api.AssignTasksResponse.tasks:type_name -> api.Task
	3,  // 10: api.Coordinator.StartJob:input_type -> api.StartJobRequest
	5,  // 11: api.Coordinator.CommitJob:input_type -> api.CommitJobRequest
	7,  // 12: api.Coordinator.ReportManifest:input_type -> api.ReportManifestRequest
	9,  // 13: api.Worker.AssignTasks:input_type -> api.AssignTasksRequest
	11, // 14: api.Worker.Heartbeat:input_type -> api.HeartbeatRequest
	4,  // 15: api.Coordinator.StartJob:output_type -> api.StartJobResponse
	6,  // 16: api.Coordinator.CommitJob:output_type -> api.CommitJobResponse
	8,  // 17: api.Coordinator.ReportManifest:output_type -> api.ReportManifestResponse
	10, // 18: api.Worker.AssignTasks:output_type -> api.AssignTasksResponse
	12, // 19: api.Worker.Heartbeat:output_type -> api.HeartbeatResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_internal_api_ingest_proto_init() }
func file_internal_api_ingest_proto_init() {
	if File_internal_api_ingest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_ingest_proto_rawDesc), len(file_internal_api_ingest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_internal_api_ingest_proto_goTypes,
		DependencyIndexes: file_internal_api_ingest_proto_depIdxs,
		MessageInfos:      file_internal_api_ingest_proto_msgTypes,
	}.Build()
	File_internal_api_ingest_proto = out.File
	file_internal_api_ingest_proto_goTypes = nil
	file_internal_api_ingest_proto_depIdxs = nil
}
